### PR TITLE
Make browser line appear less condescending

### PR DESCRIPTION
**Pull request by tjguk**

### CODE REVIEW

**Comment by doismellburning** [comment]
A++++++++ fully support

**Comment by ntoll** [comment]
Thanks Tim.

Travis is complaining about this. :-(

It appears that `HEAD detached at FETCH_HEAD` is the error (which is a bit of a surprise). Is GIT configured correctly. I'm not a Travis user so at a bit of a loss as to where to start.

N.

**Comment by d0ugal** [comment]
It failed due to this check: https://github.com/PyconUK/pyconuk.org/blob/master/pre-flight-checks.sh#L66-L69

... but I don't really understand it. Do you need to build locally and include the result in the commit?

**Comment by tjguk** [comment]
Well it's just one line; if someone else wants to make the same change 
from their setup, please feel free. I'm not sure what to suggest...

**Comment by inglesp** [comment]
Hi everyone.  @d0ugal's right about the failing check, which is caused by there being uncommitted changes in the `output/` directory after Travis has built the site.

To fix this, @tjguk should run `make build` locally, which will update the `output/` directory, and push these changes.

This is mentioned in the `README`, but it's not very clear.  Any suggestions for clarification here welcome.

**Comment by tjguk** [comment]
Thanks, Peter. I'll do that. (TBH I didn't even look at the README, 
assuming that a simple text change would "just work". Mea culpa).

**Comment by d0ugal** [comment]
A 'CONTRIBUTING.md' file would be a bit more prominent.

https://github.com/blog/1184-contributing-guidelines

**Comment by inglesp** [comment]
Merged -- thanks @tjguk.

**Pull request merged**
