### PR TITLE
Added sponsorship page to template.

### PR DESCRIPTION
**Pull request by snim2**
See email from Mary.

### CODE REVIEW

**Comment by inglesp** [comment]
This makes the heading look a bit wonky to me:

image

**Comment by ntoll** [comment]
Can we not remove "Home" and make the flash image in the middle a link to "Home" to even things out..?

**Comment by inglesp** [comment]
I've tried and failed to do this.  Any CSS-savvy volunteers?

**Comment by ghickman** [comment]
I'll do my best to do this when I fix #14 since I've got to put my CSS spelunking kit on anyway.

**Comment by ghickman** [comment]
I've removed the Home URL and made sure the banner/flash image in the middle is clickable across the entire element (the nav element was obscuring most of its click target before).

I've also shuffled around the menu items to balance them around the banner:

**Comment by inglesp** [comment]
Very nice, thanks.

**Pull request merged**
