### PR TITLE
Updated link to Ibis as the affiliate link.

### PR DESCRIPTION
**Pull request by ntoll**
This branch introduces one change:
- The link to the Ibis is now via our affiliate link which brought us untold riches (about £30) at last year's conference.

:-)

### CODE REVIEW

**Comment by rwillmer** [comment]
Just FYI, it wasn't the Ibis link that brought the untold riches, it was the other links on the old wiki page. The Ibis rate needed you to telephone them so the weblink didn't work.

If anyone wants to maximise the revenue, then go back to the old wiki page and take all the old affiliate links over to the new page; I'll do it when I can, but I have customer deadlines to meet so won't have any spare time until that's done.

**Comment by inglesp** [comment]
Hey @rwillmer -- can you define "untold riches" please?

**Comment by rwillmer** [comment]
Not quite sure what you're asking, @inglesp. I'm just quoting ntoll's phrase..

I think last year I handed over about 20-30 quid. No idea what this year might bring.

**Comment by ntoll** [comment]
"No idea what this year might bring."

UNTOLD RICHES!!!

(note - "untold" may include anything from 0-infinity, that's why it's untold. Perhaps "undefined" might have been a better word to use, but it's far too JavaScript-y for my liking.)

:-)

**Pull request merged**
