### PR TITLE
Added badges and lanyards.

### PR DESCRIPTION
**Pull request by snim2**
Default price. See email from Mary.

### CODE REVIEW

**Comment by inglesp** [comment]
Hi @snim2 -- the change itself looks great, but the Travis checks are failing because you've not committed the changes to the `output/` branch.  Could you run `make build` (or just `wok`) and then commit and push the changes that doing creates?

**Comment by inglesp** [comment]
And if you've got any suggestions for how to make it easier not to be caught out by this, let me know.

**Comment by snim2** [comment]
Ah, so this happened because I edited the files from the in-browser editor in GitHub. I'll check everything out when I'm back in a sensible operating system later today. In the mean time I'll generate a PR to clarify this in the README.

**Comment by inglesp** [comment]
Ah -- it hadn't occurred to me that the new way of doing things would prevent us from using GH's in-browser editor.

**Comment by d0ugal** [comment]
@inglesp I've not followed this at all, but can't the build just happen on Travis?

**Comment by snim2** [comment]
@d0ugal I'll have a go...

**Pull request merged**
