### PR TITLE
Skeleton 2016 site

### PR DESCRIPTION
**Pull request by snim2**
This PR makes the following changes:
1. Removes all 2015 content and schedule
2. Bumps the year to 2016
3. Changes the dates of the conference to the 2016 dates
4. Removes some 2015 specific text
5. Disables the flat schedule hook
6. Marks all sponsorship as unclaimed
7. Removes the list of 2015 sponsors
8. Renames the Science track

The idea is to create a skeleton site for 2016 which can be merged into master following the 2015 event and Society AGM.

Much more will need to be done, including creating new CfP forms, updating the banner and other assets, writing some new text, etc.

### CODE REVIEW

**Comment by inglesp** [comment]
I haven't reviewed this in detail, but I'd like us to completely rethink how we do sponsorship next year, so could you remove the sponsorship page?

In short, we've ended up promising something different to each sponsor, and actually getting that right is going to be a lot more work that it could have been.  (Don't worry, I'm more-or-less on it...)  Next year we should go for something far simpler -- but this isn't something I want to be thinking about until we've put 2015 to bed.

On that subject, what's the motivation for getting the 2016 website out there immediately?  It obviously makes us look like we know what we're doing, but I wondered whether there was another reason.

**Comment by snim2** [comment]
Will do.

Motivation - every year we have a few queries of the "will there be a conference" type, which this would fix. Secondly, some years we have been "too late" to get sponsorship from some companies.

Also, there are a few Sci Track ideas I have which would benefit from being announced early.

That said, it is entirely up to us when we merge with the master branch. Starting early doesn't have to mean launching early, but it seems sensible to me.

**Comment by inglesp** [comment]
Makes sense, thanks @snim2!

**Comment by snim2** [comment]
I just did a `pull --rebase upstream master` on this PR, which should make it possible to merge.

However, this PR should be set up to merge into a new branch called `2016-site` and **not** into `master`.

Therefore, I think this can be safely merged now into the `2016-site` branch, ready for people to sprint on (but please do check I haven't messed this up!).

/cc @inglesp @doismellburning

**Comment by snim2** [comment]
This PR needs another `git pull --rebase upstream master`, which I will do later today. Probably the `/todo` page needs to be kept, and updated as we go.

Are there any other pages that should not be deleted or stripped of 2015 specific content?

Thanks.

**Comment by inglesp** [comment]
Hi @snim2 -- I've just merged this into the `2016-site`.  Sorry I missed this during the conference (was it only 27 days ago?!).

What now needs doing?

**Comment by snim2** [comment]
Good question.

This PR made the assumption that we would delete the files relevant to the 2015 site and start again with the 2016 site. In previous years we have done this by starting a new repository, which has the advantage of archiving the files somewhere, but not anywhere very easy for delegates to find. 

So whether this PR will work out depends on how that archiving is going to happen. If it would be better to rearrange the directory structure and keep the old files, then this PR needs to be closed and the branch should be deleted. The skeleton site for 2016 is still useful though, so we should find a way to cherry pick those commits.

On the other hand, if you want to go ahead with deleting these files and find another way to archive the 2015 material then I need to bring this branch up to date with `master` and make sure that any files we want to keep are still around on this branch.

**Comment by doismellburning** [comment]
For what it's worth, I'm strongly in favour of not deleting the 2015 stuff; how about we look at the model other PyCons / DjangoCons use: http://2016.djangocon.eu/ etc.

(Having just wandered in and said: "hey lets do more work", I'm very happy to contribute there as needed / if desired...)

**Comment by hawkz** [comment]
How should I best kick off the 2016 redesign? add to this PR or separately? I guess the 2016 seperate comment affects this too (Hi Kristian!)

**Comment by zeth** [comment]
Or even like we used to do http://2013.pyconuk.org/

**Comment by zeth** [comment]
So I can have an archive of 2015 on my server, or if someone can figure out
how to make two sites on github, I can point the domain at it.

**Comment by inglesp** [comment]
@hawkz:  I think this is not the place for kicking off the 2016 redesign.  Could you drop an email to the list setting out what you think needs to be done with respect to design work?  (I don't think there's any rush -- we can re-use the assets we've got for the time being.)

**Comment by inglesp** [comment]
@zeth:  I'm pretty sure that's what @doismellburning was suggesting!  @doismellburning, are you in a position to make this happen?

**Pull request merged**
