### PR TITLE
Add sponsors' logos to index

### PR DESCRIPTION
**Pull request by inglesp**
This adds sponsor logos to the index page.  I wasn't able to fix the CSS in #107 so have started again with the noddiest thing I could come up with.

screen shot 2015-08-20 at 20 18 10

### CODE REVIEW

**Comment by ntoll** [comment]
Bank of America (who keep hassling me about this) should be at the top.

**Comment by ntoll** [comment]
Also, our sponsors can be found on that spreadsheet too. @moonmar has been keeping track of the logos she's been sent.

**Comment by inglesp** [comment]
"Also, our sponsors can be found on that spreadsheet too."  I know -- I've contacted all the sponsors on that sheet, apart from BAML.  These logos are from the sponsors who've replied to my email.  I'm not going to go hunting for logos from companies who don't reply to email.

@moonmar -- if you have been sent logos from sponsors other than those in the image above, please let me know.

I don't have the BAML logo -- @ntoll, please could you send me a suitable one?  Alternatively, you could merge this and then create your own PR.

**Comment by inglesp** [comment]
Try this:

image

**Pull request merged**
