### PR TITLE
Sponsorshome

### PR DESCRIPTION
**Pull request by hawkz**
Added sponsors into different groupings to the home page, let me know if I missed anything.

Naturally we'll need to update the list before going live with this.

### CODE REVIEW

**Comment by ntoll** [comment]
You little beut... bonzer! :-)

Two things:
- I'm not sure it's supposed to look like this (see attached screenie)
- Can the sponsors go above the blurb but below the logo?

huh

**Comment by inglesp** [comment]
I'm afraid this looks a bit wonky on my machine (OSX 10.9.5, Chrome 44.0.2403.130).

image

**Comment by ntoll** [comment]
@inglesp snap. I'm on Debian Jessie with latest "official" Firefox.

**Comment by inglesp** [comment]
Closing, since sponsor logos have been added in #117.

**Pull request closed without merging**
