### PR TITLE
Initial Schedule Changes

### PR DESCRIPTION
**Pull request by zeth**
I have more radical ideas to come but will save those if we need more space. The more obvious and conservative changes represented by this pull request include:
- Added back room 4 to Friday.
- Added in non-science workshops to help calculate space. Not all of them get exactly 3 hours because there is just not enough periods of unbroken space to do that.
- Let some workshops run over a little into the 2 hour lunch (which can actually help stagger delegates)

To see the current number of free talk slots, you can use:

```
cat schedule.rst | grep -o XTalk | wc -l
```

This currently gives 67. This does not include science track talks.

### CODE REVIEW

**Comment by inglesp** [comment]
Good work that @zeth.

I'm running out of steam to look at this properly tonight, but everybody with an interest should make sure they find at least ten minutes tomorrow to look over this and think through any potential problems.

My only observation is that it's too early to start putting workshops into slots: firstly, I'm quite keen that we don't take at least one of those workshops (I think it had a very weak proposal, the proposer hasn't responded to my feedback, and the proposer has submitted several talks that I think we should prefer) and secondly, we don't yet know that the workshoppers will be able to give their workshop on the days that we've allocated.

Apart from that -- great stuff.  Go and have a drink!

**Comment by zeth** [comment]
```
My only observation is that it's too early to start putting workshops into slots:
```

Fair enough. As they are such a massive allocation of time and have such massive side-effects on the placement of everything else, could you perhaps please review the workshops first?

   firstly, I'm quite keen that we don't take at least one of those workshops

Perversely, from my perspective that is great news, every workshop takes up 5-6 talks worth of space so reject away :)

**Comment by zeth** [comment]
Workshop names are now removed and the placeholder XWorkshop is in place.

```
cat schedule.rst | grep -o XWorkshop | wc -l
6
```

**Comment by ntoll** [comment]
This is great work @zeth - kudos to you.

A couple of points spring immediately to mind:
- There will be a huge amount of equipment (think Raspberry Pis, Monitors, robots, general stuff) and probably a lot of kid-related mess that'll need putting away post-kids' day. Sticking a workshop right after it is basically impossible. It took us at least an hour to put everything away last year.
- The kids' lightning talks - there will be huge logistical cat-herding exercise getting the kids and their parents over to the main hall to start at 3:30pm. There will need to be enough room in the hall for the kids and parents. I also notice there's a keynote right up until the 3:30 slot. I estimate it'll take at least 15 minutes to get kids/parents over and sat down. Perhaps the keynote can be 45mins..?

This latter problem has only just occurred to me. I believe giving the kids an opportunity to lightning talk to the conference is a brilliant thing to do. However, the logistics of this give me the collywobbles. Suggestions on a postcard please!

**Comment by lukestanley** [comment]
Not sure this is the best thread but I want to remind people for last
minute changes due to illness, or whatever reason, I can have SMS schedule
updates sent out. So we shouldn't worry excessively about changes, we are
programmers. We aren't incapable of smooth updates all of the time :)

Are we capturing numbers yet?
I did ask Ntol about an account in the new ticket system. I'm going to use
Twillio.

**Pull request merged**
