### PR TITLE
Add Education Day on Friday.

### PR DESCRIPTION
**Pull request by zeth**

### CODE REVIEW

**Comment by inglesp** [comment]
Looks good, but it's really hard to review this because all the column widths have changed -- could we avoid this in future?

Using the tool in #163 (any chance that could be merged?) has helped.

**Comment by zeth** [comment]
"Looks good, but it's really hard to review this because all the column widths have changed -- could we avoid this in future?"

Not really, that is kinda the whole point. Cannot dumb down the whole thing just for a bad diff implementation.

**Comment by inglesp** [comment]
OK -- sorta take your point.  GH usually highlights the parts of lines that have changed, like this:

image

It hadn't done so here, so I'd assumed that more had changed than actually had.

Let me know if you've got any better suggestions for reviewing this kind of diff.

**Comment by zeth** [comment]
Build the site then local in one window, live one in one window, then apply
mark one eyeball!

There was an idea next year to go AI and have George's talk review app end
with a schedule, that might reduce some of the pain.

**Pull request merged**
