### PR TITLE
Add HP logo

### PR DESCRIPTION
**Pull request by inglesp**

### CODE REVIEW

**Comment by ntoll** [comment]
Have we added the Fry-IT logo..?

**Comment by inglesp** [comment]
No, cos they haven't sent it to us.  Chasing sponsors is on today's list.

**Comment by ntoll** [comment]
We already have it somewhere - in the old repos?

**Comment by inglesp** [comment]
It's not just Fry IT whose logo we're missing.

Sending a reminder email is quick -- but I'm not spending my Saturday hunting around old repos (what old repos?) to find something that I've asked to be sent.

**Comment by ntoll** [comment]
Turns out Fry-IT have just changed their logo. ;-)

Email away (was trying to save you some effort).

I'm off to watch my son play football (in the rain). Will be back later.

**Pull request merged**
