### PR TITLE
Shuffle Shuffle

### PR DESCRIPTION
**Pull request by zeth**
Minor schedule updates.

### CODE REVIEW

**Comment by inglesp** [comment]
Looks mostly good, except that I think the careers clinic should be in a smaller room and last for two hours.

**Comment by zeth** [comment]
Would be a good moment to merge now, as until its merged, it will be hard to accept non-zeth contributions because of the different tabulation.

**Comment by inglesp** [comment]
This is almost impossible to review!  Because of the changes to column widths, almost every line has changed, so it's very hard to work out what changes are important.

With that caveat, I think it's all fine, except for something I missed the first time round: this PR moves the wrong talk from the Friday to the Saturday.  It should be "Dispelling py.test magic" that moves, not "Document all the things".

**Comment by zeth** [comment]
Best to use wok or rst2html I guess to generate rendered thing to look at.

**Comment by zeth** [comment]
Peter, good find. I think it is okay now?

**Comment by inglesp** [comment]
Yup!

**Pull request merged**
