### PR TITLE
Science Track Content

### PR DESCRIPTION
**Pull request by zeth**
Science track content as defined by SM.

### CODE REVIEW

**Comment by snim2** [comment]
Was this one finished?

**Comment by inglesp** [comment]
@snim2, are you asking because you don't think it's finished?

**Comment by snim2** [comment]
I thought there was one empty talk slot that we were still discussing?

**Comment by zeth** [comment]
On 3 July 2015 at 02:08, Sarah Mount notifications@github.com wrote:

> I thought there was one empty talk slot that we were still discussing?

Yeah no problem. When the talk is picked I will put it in.

**Comment by snim2** [comment]
For some reason I thought I saw a commit which added an actual talk in the empty slot. Maybe that got reverted or perhaps I just misread the commit message. No matter, the file that was merged seems fine.

I'll get back to you about that slot later today, I have an idea, but I need to liaise with one of the track attendees...

**Pull request merged**
