### PR TITLE
Generate an iCal schedule

### PR DESCRIPTION
**Pull request by wjt**
Hastily bodged together, all criticism very welcome.

### CODE REVIEW

**Comment by inglesp** [comment]
Hi @wjt -- this looks like a great addition!  Thanks for working on it.

**Comment by wjt** [comment]
I've only tested in a few clients – some show both the URL field and the description, linkified; others (I'm looking at you, Thunderbird) don't show the URL and show the description as unlinkified plain text. Not sure what the most widely-appreciated representation would be.

Also some of the events with extremely long titles (ie the sprints) look a bit ridiculous, might be worth splitting everything after the first line into the description. Afraid I don't have much time to spend finessing this!

**Comment by moreati** [comment]
Tested with Google Calendar -> Add by URL. LGTM

**Comment by avengerpenguin** [comment]
I've added this to Google Calendar, but everything is an hour ahead of what times I see on http://www.pyconuk.org/schedule/flat/ is there a timezone issue with this change?

**Comment by wjt** [comment]
@avengerpenguin ahem, I didn't include any timezones in the iCal file – all the clients I tried treated them as local times so they worked out fine, but maybe your client treats them as UTC? (Or is your local time not BST?)

**Comment by avengerpenguin** [comment]
@wjt I just put it in Google Calendar which I assume it set to UK time... are you saying I should make sure I am set to UK time and it'll be fine?

**Comment by avengerpenguin** [comment]
No, Google Calendar is definitely localised to UK. I just added via URL and that's what it's done.

**Comment by wjt** [comment]
@avengerpenguin maybe – I think Google Calendar has a “floating time” mode which means “always local”, too, but not sure if you can apply that to a whole calendar

**Comment by avengerpenguin** [comment]
I might try Thunderbird so it works offline too.

**Pull request merged**
