### PR TITLE
Revectorized the crown graphic

### PR DESCRIPTION
**Pull request by helenst**
I wanted to incorporate the crown into some of our Django Girls swag but couldn't get hold of a vector copy.

So I recreated it from a Keep Calm crown, the Python logo and a little bit of duct tape.

I thought this may be useful to somebody else in future. :)

:crown::snake:

### CODE REVIEW

**Comment by hawkz** [comment]
Nice work :+1:

**Comment by hawkz** [comment]
Thinking further, should I dump all of my originals somewhere in the repo? where would make sense?

**Comment by zeth** [comment]
Sounds like a good idea. Make a new folder if there isn't anywhere
relevant. There is also the PyCon UK society github as well which may be
better for somethings, I don't know.

**Comment by snim2** [comment]
I'd say keep the assets in this repo, where they will be used -- saves people from cloning two separate repos just to work on the site. The Society repo is mainly for the legal stuff.

**Pull request merged**
