### PR TITLE
More hotel links and a disclaimer

### LINKED ISSUE #60: Hotels don't have affiliate links

### PR DESCRIPTION
**Pull request by rwillmer**
That's all the hotels that Booking.com covers.
Closes #60

### CODE REVIEW

**Comment by ghickman** [comment]
@rwillmer – thanks for these changes!

Could you fix the name of the conference before I merge please? The travis output shows you which line the error is on =)

**Comment by rwillmer** [comment]
Happy to make the change but can you tell me what the official 'right' name is? I can think of many variants that I could try next...

**Comment by ghickman** [comment]
@rwillmer – thanks! "PyCon UK"

**Comment by rwillmer** [comment]
okeydoke, try that?

P.S. that namecheck is neat, will have to check out how you do that :)

George Hickman wrote:

> "PyCon UK"

**Comment by ghickman** [comment]
@rwillmer – thank you! (sorry for the pedantry)

You can see the check [here](https://github.com/PyconUK/pyconuk.org/blob/master/pre-flight-checks.sh#L51) along with the other preflight checks =)

**Pull request merged**
