### PR TITLE
Small change in wording of science track blurb

### PR DESCRIPTION
**Pull request by snim2**
Suggested by @russel

### CODE REVIEW

**Comment by zeth** [comment]
You put digital humanities scholar in, the conference now owes me £38 :)

Anyway what's the difference between digital humanist and digital humanities scholar? They keep changing the name, I still like computing in the humanities :)

**Comment by snim2** [comment]
Feedback from @russel was that it sounded too much like the other sort of Humanist.

**Comment by zeth** [comment]
Well all the early humanists were Christians, just recently after Lenin and
the other communists and idiots, people think humanism is about secularism
rather than a commitment to learning the truth without prejudice.

**Comment by snim2** [comment]
Well, it was a mere accident of history that the far-left became secular. Feuerbach has a lot to answer for.

**Comment by zeth** [comment]
Well all those Europeans, what can we do? I think you should consider
renaming it to the research track now, since digital humanists might hide
under a duvet of insecurity by the word science.

On a more serious note, I think it would actually describe better what you
have felt your way towards.

**Comment by snim2** [comment]
It would, but it is a bit late now to change the name. I have made this Issue 1 on the 2016 planning repo:

https://github.com/PyconUK/planning2016/issues/1

**Comment by zeth** [comment]
I personally don't consider it too late to change the title as we are still
a few months away and anyone you reached with the science label, well you
still reached.

However, having thought about it for 2 mins, I am not sure the single word
research is the best title either, as it might imply that it is about CS
research into Python, rather than using Python for Research... It is not
easy.

**Comment by snim2** [comment]
I think it would be confusing to change the name now as we have already sent out blog posts, etc. Let's take some time to think it over and come up with something really good for next year. In the mean time, do try and entice your friends from the humanities over...

**Comment by zeth** [comment]
I'll see what I can do :)

**Pull request merged**
