### PR TITLE
Schedule updates

### PR DESCRIPTION
**Pull request by zeth**
Add intro to self-help learning Python thing and the code clinc things.

### CODE REVIEW

**Comment by zeth** [comment]
Ok this has reached a point where it is needs merging. A lot has moved around now I have figured out which rooms represent which column.

**Comment by ghickman** [comment]
@zeth – this is looking great! I see a few XTalks left, I assume that means you've got more scheduling to do but want to get what you've done merged (which I'm happy to do, but want to check you're not planning on adding more first =)

**Comment by zeth** [comment]
I have added everything that Peter et al has approved so far so the XTalks are actually free at the moment. Several speakers have submitted two talks and we might have left off something.

Yep please do merge.

**Comment by ghickman** [comment]
:+1:

**Pull request merged**
