### PR TITLE
Replace Programme in the site menu with the flat schedule

### PR DESCRIPTION
**Pull request by moreati**
Also
- Adds a switcher to choose between flat and tabular schedule
- Moves the flat schedule to /schedule/
- Moves the tabular schedule to /schedule/tabular

This means /programme/ is no longer reachable by an obvious link.
Given we're T - 10 days & only the lunchtime CfP remains - is that a problem?

### CODE REVIEW

**Comment by zeth** [comment]
I think we shouldn't change the location of the tabular one; that just confuses people. Better is:
- /programme - the flat schedule, which links to ->
  - /schedule - the tabular schedule
  - /callforevents - call for lunchtime events

**Comment by zeth** [comment]
By that I mean people have been looking at /schedule for the table for months, so lets call the "flat schedule" programme so we don't have to use these adjectives all the time.

**Comment by zeth** [comment]
Could even use namespaces a little for the new page:
- /programme - the flat schedule, which links to ->
  - /schedule - the tabular schedule
  - /programme/callforevents - call for lunchtime events

**Comment by moreati** [comment]
Zeth, I disagree.
1. Having different words ('programme' and 'schedule') seems more confusing to me, than different adjectives applied to a single word ('flat schedule' and 'tabular schedule'). The former implies to me they are distinct things, the latter implies they're different views of one thing.
   
   I worry we'd get questions like 
   
   > Why is there a programme _and_ a schedule? Which should I follow?
2. I don't think moving the tabular schedule from `/schedule` to `/schedule/tabular` would confuse people. However, if it did then wouldn't moving `/programme` to `/programme/callforevents` confuse people as well?

**Comment by zeth** [comment]
Well on your point 2, the amount of people that will care about submitting
a new lunchtime event is between 5 (in my dreams) and 0 (in reality) whereas
400+ people have been looking at the table at /schedule.

Cool URIs don't change and all that.

**Comment by zeth** [comment]
For me the flat schedule is more about forward planning what you want to look at when you are relaxed, whereas the table is for looking in a rush. So the table needs to be easily findable where people expect it.

Incidentally, the original plan before we separated out the abstracts (for ease of community editing) was that it would be a long form version that would end being roughly what the flat version looks like now.

**Comment by inglesp** [comment]
A data point: the flat schedule renders far better on mobile devices than the tabular one.

For that alone, I'm in favour of Alex's changes.

Anybody else got an opinion?

**Comment by zeth** [comment]
> A data point: the flat schedule renders far better on mobile devices than
> the tabular one.

I am not advocating not having the flat one. I am just advocating not
changing URL of the old one.

**Comment by inglesp** [comment]
OK, so how about:
- keeping the tabular schedule at /schedule and the flat schedule at /schedule/flat
- using the nice links that @moreati's added to allow people to easily switch between the two
- replacing Programme with Schedule in the navbar, which links to the flat schedule

?

**Comment by zeth** [comment]
Perfect.

**Comment by moreati** [comment]
Agree with @zeth on @inglesp's suggestion. Now implemented in 5df9975.

**Pull request merged**
