### PR TITLE
Add Patch to sprints.

### PR DESCRIPTION
**Pull request by zeth**

### CODE REVIEW

**Comment by zeth** [comment]
Thanks for the merging, any idea why the site did not rebuild?

**Comment by doismellburning** [comment]
https://github.com/PyconUK/pyconuk.org/pull/198#issuecomment-141785163

**Comment by inglesp** [comment]
I've just deployed manually, by running `./deploy.sh` from the root of the repo.

**Comment by zeth** [comment]
Thanks mate

**Pull request merged**
