### PR TITLE
Shuffle down talks on Sunday for keynote space

### PR DESCRIPTION
**Pull request by zeth**

### CODE REVIEW

**Comment by zeth** [comment]
I could make another row on Friday but then we will have blank spaces and things will be more rushed.

This is ready for merging now, at least the schedule is now more accurate, even though it has one talk too many.

**Comment by inglesp** [comment]
Good shuffling!

By "one talk too many", do you mean the Drogulus talk which is on the schedule but doesn't have a time?

One problem that I've spotted: the Building Async Microservices workshop is now three and a half hours long, while the Event-Sourced Domain Models in Python workshop that follows it is now only an hour and a half.  These were originally two and a half hours each -- could this be fixed please?

**Comment by zeth** [comment]
"By "one talk too many", do you mean the Drogulus talk which is on the schedule but doesn't have a time?"

That is right, Nick is currently giving the talk in a parrell universe or something :)

Good find on the workshops, I totally mixed that.

**Comment by inglesp** [comment]
Still think it looks a bit odd to have the Drogulus talk floating like that (a fiver says somebody'll point it out to us) but I'm merging this now in the interests of getting something up there so that we can tell the people whose talks have been moved about their new slots.

**Comment by ntoll** [comment]
OK... here's the solution. I drop the drogulus talk. It would have been a pretty last minute thing anyway and looking at the sort of work I'm going to be doing in the weeks up to PyCon UK I think it would make my life easier if I had one less thing to think about.

So, this is me officially asking for my talk to be removed from the programme.

Yay... Naomi has space. :-)

N.

**Comment by zeth** [comment]
Well I still believe we will get plenty more cancellations because the conference is made out of people. So I don't think you need to fall on your sword Nick, unless you don't actually want to give the talk.

**Comment by ntoll** [comment]
@zeth :-) seriously, it would take one more thing off my ever expanding to-do list which is a good thing. I'll have other opportunities to give the talk later this year and in the new year. Honestly, it'd be a relief and I can kick back on the Sunday. ;-)

**Pull request merged**
