### PR TITLE
Revert "fix overflow of scheduals to work on screens  < 1024"

### PR DESCRIPTION
**Pull request by zeth**
Reverts PyconUK/pyconuk.org#189

### CODE REVIEW

**Comment by zeth** [comment]
The problem is not the width of the table, the problem is that 2/3 screen is white space, the real solution is to fix the CSS not make the education track etc hidden.

**Comment by zeth** [comment]
Its difficult but we need mobile fix without breaking desktop.

**Comment by inglesp** [comment]
That's odd -- it looked fine on my laptop.

**Comment by zeth** [comment]
Did you try Firefox?

**Comment by zeth** [comment]
It broke the tabular schedule on Firefox but the thinking was a good idea but the CSS change needs refinement.

**Pull request merged**
