### PR TITLE
Adding cards against online sprint to schedule

### PR DESCRIPTION
**Pull request by grimpunch**
Just adding a last minute sprint to the schedule!

### CODE REVIEW

**Comment by ghickman** [comment]
@grimpunch – thanks for adding this. Unfortunately I think it's clashing with something else I just merged, would you mind dealing with the conflict?

**Comment by grimpunch** [comment]
@ghickman  I think it's up to date now?

**Comment by ghickman** [comment]
@grimpunch – thanks!

**Comment by grimpunch** [comment]
if you're able can you deploy the site please? :)

**Comment by doismellburning** [comment]
`master` is auto-deployed

**Comment by doismellburning** [comment]
(`us-east-1` is having problems; I suspect that is causing Travis sadness and woe. Appropriate libations are being offered up to the Amazons)

**Comment by grimpunch** [comment]
Thanks for the update :+1:

**Pull request merged**
